CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
SPELL_CSPELL_PRE_COMMANDS:
  - command: npm install @cspell/dict-win32 && ls && ls node_modules
    cwd: "workspace"
DISABLE:
  - COPYPASTE
  - REPOSITORY
DISABLE_LINTERS:
  - JSON_V8R
  - YAML_V8R
DISABLE_ERRORS_LINTERS:
  - YAML_YAMLLINT