CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
DISABLE:
  - COPYPASTE
  - REPOSITORY
DISABLE_LINTERS:
  - JSON_V8R
  - YAML_V8R
DISABLE_ERRORS_LINTERS:
  - YAML_YAMLLINT

# Cspell variables
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT # cspell.config.yaml contains import: ["@cspell/dict-win32/cspell-ext.json]
SPELL_CSPELL_PRE_COMMANDS:
  - command: npm install @cspell/dict-win32
    cwd: "workspace"

